services:
  - type: web
    name: mern-task-server
    env: node
    plan: free
    repo: https://github.com/yashas98765/MERN-Stack-Internship-Assignment
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: "${MONGO_URI}"
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
